version: '3.9'

volumes:
  cloudflared-home:

services:
  cloudflared-kory33-net:
    build:
      context: ./cloudflared
      dockerfile: ./Dockerfile
    image: local-cloudflared-image
    volumes:
      - cloudflared-home:/root
  intercom:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      INTERCOM_DISCORD_BOT_TOKEN: ${INTERCOM_DISCORD_BOT_TOKEN}
