version: '3.9'

volumes:
  cloudflared-home:
  portainer_data:

services:
  cloudflared-kory33-net:
    build:
      context: ./cloudflared
      dockerfile: ./Dockerfile
    image: local-cloudflared-image
    volumes:
      - cloudflared-home:/root
    restart: always

  portainer:
    image: portainer/portainer-ce:2.5.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  intercom:
    build:
      context: ./intercom
      dockerfile: ./Dockerfile
    image: local-intercom-server
    env_file:
      - intercom.env
    restart: always
