version: '3.9'

volumes:
  cloudflared-home:

services:
  cloudflared-kory33-net:
    build:
      context: ./cloudflared
      dockerfile: ./Dockerfile
    image: local-cloudflared-image
    volumes:
      - cloudflared-home:/root
  intercom:
    build:
      context: ./intercom
      dockerfile: ./Dockerfile
    image: local-intercom-server
    env_file:
      - intercom.env
