global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'intercom_server'
    static_configs:
      - targets:
        - 'intercom:8081'
  - job_name: 'intercom_blackbox_http'
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    params:
      module: [ipv4_http_401]
    static_configs:
      - targets:
        - https://intercom.kory33.net
        - http://intercom:8080
