version: '3.9'

volumes:
  servers_repository:

services:
  controller:
    build:
      context: ./controller
      dockerfile: ./Dockerfile
    image: oracle-cloud-gp-servers-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/github/controller-trigger/:/root/controller-trigger/
      - servers_repository:/root/servers-repo/
      - /home/ubuntu/oracle-cloud-gp-servers/services/intercom.env:/tmp/services/intercom.env
    restart: always
