name: Restart services on Cloud Compute
on:
  push:
    branches:
    - master
    paths:
    - 'services/**'
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
    - name: Execute controller-restart
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.CONTROLLER_HOST }}
        key: ${{ secrets.CONTROLLER_AUTH_KEY }}
        username: github
        port: 22
        script: touch /home/github/controller-trigger/restart-services
